# Generated by Django 5.2.17 on 2026-08-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
